### ISSUE TITLE
Check the status of the MySQL replication

### ISSUE THREAD

**Issue by cornelinux** [privacyidea/privacyidea-appliance#35]
We should be able to easily check the status of the mysql replication.

   mysql> SHOW SLAVE STATUS;
   mysql> SHOW MASTER STATUS;

**Comment by cornelinux** [comment]
I am not sure, if we have enough access rights. The pi-appliance only knows the ``pi`` sql password but not the root password.

On the other hand: We are running as system user ``root``!

**Comment by cornelinux** [comment]
This is an important feature to find simple errors. Even I need to check each time, how to find the problem. Then you need to find the mysql root passwort...
this is a bit cumbersome. An output in the pi-appliance would be helpful.

**Comment by fredreichbier** [comment]
Yes, this is a good idea.
When setting up replication, we use the credentials stored in ``/etc/mysql/debian.cnf``. I guess we could just do the same (as we run the appliance tool as root):
```
echo "SHOW SLAVE STATUS" | mysql --defaults-extra-file=/etc/mysql/debian.cnf pi
```

**Comment by fredreichbier** [comment]
OK, so the above command seems to be working indeed.
But I guess we shouldn't display the whole output. Here are the values (note that the second node is offline) -- which ones should we pick?
```
# echo "SHOW MASTER STATUS\G" | mysql --defaults-extra-file=/etc/mysql/debian.cnf pi 
*************************** 1. row ***************************
             File: mysql-bin.000002
         Position: 154
     Binlog_Do_DB: pi
 Binlog_Ignore_DB: 
Executed_Gtid_Set: 
# echo "SHOW SLAVE STATUS\G" | mysql --defaults-extra-file=/etc/mysql/debian.cnf pi 
*************************** 1. row ***************************
               Slave_IO_State: Connecting to master
                  Master_Host: 192.168.33.202
                  Master_User: replicator
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000002
          Read_Master_Log_Pos: 22155
               Relay_Log_File: appliance1-relay-bin.000005
                Relay_Log_Pos: 4
        Relay_Master_Log_File: mysql-bin.000002
             Slave_IO_Running: Connecting
            Slave_SQL_Running: Yes
              Replicate_Do_DB: 
          Replicate_Ignore_DB: 
           Replicate_Do_Table: 
       Replicate_Ignore_Table: 
      Replicate_Wild_Do_Table: 
  Replicate_Wild_Ignore_Table: 
                   Last_Errno: 0
                   Last_Error: 
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 22155
              Relay_Log_Space: 154
              Until_Condition: None
               Until_Log_File: 
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File: 
           Master_SSL_CA_Path: 
              Master_SSL_Cert: 
            Master_SSL_Cipher: 
               Master_SSL_Key: 
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 2003
                Last_IO_Error: error connecting to master 'replicator@192.168.33.202:3306' - retry-time: 60  retries: 61
               Last_SQL_Errno: 0
               Last_SQL_Error: 
  Replicate_Ignore_Server_Ids: 
             Master_Server_Id: 0
                  Master_UUID: bee59d63-e653-11e7-91f7-0800271149c9
             Master_Info_File: /var/lib/mysql/master.info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind: 
      Last_IO_Error_Timestamp: 180111 12:24:43
     Last_SQL_Error_Timestamp: 
               Master_SSL_Crl: 
           Master_SSL_Crlpath: 
           Retrieved_Gtid_Set: 
            Executed_Gtid_Set: 
                Auto_Position: 0
         Replicate_Rewrite_DB: 
                 Channel_Name: 
           Master_TLS_Version: 
```
I started with:
* ``MASTER``: the values of ``File`` and ``Position``
* ``SLAVE``: the values of ``Slave_IO_State``, ``Last_IO_Error_Timestamp`` and ``Last_IO_Error``

What do you think?
